[book]
authors = ["Fuel Labs"]
language = "en"
multilingual = false
src = "src"
title = "Fuel Docs Hub"

[output.html]
default-theme = "fuel-dark"
preferred-dark-theme = "fuel-dark"

[output.html.search]
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
