/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.60.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

export type { CounterContractAbi } from './CounterContractAbi';

export { CounterContractAbi__factory } from './factories/CounterContractAbi__factory';
