/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import type {
  BigNumberish,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export type ErrorInput = Enum<{ SameBlock: [], HasNotWon: BigNumberish }>;
export type ErrorOutput = Enum<{ SameBlock: [], HasNotWon: number }>;

interface CoinFlipAbiInterface extends Interface {
  functions: {
    attack_success: FunctionFragment;
    coin_flip: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'attack_success', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'coin_flip', values: [boolean]): Uint8Array;

  decodeFunctionData(functionFragment: 'attack_success', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'coin_flip', data: BytesLike): DecodedValue;
}

export class CoinFlipAbi extends Contract {
  interface: CoinFlipAbiInterface;
  functions: {
    attack_success: InvokeFunction<[], boolean>;
    coin_flip: InvokeFunction<[guess: boolean], boolean>;
  };
}
