/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface HelloWorldAbiInterface extends Interface {
  functions: {
    attack_success: FunctionFragment;
    hello_world: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'attack_success', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'hello_world', values: []): Uint8Array;

  decodeFunctionData(functionFragment: 'attack_success', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'hello_world', data: BytesLike): DecodedValue;
}

export class HelloWorldAbi extends Contract {
  interface: HelloWorldAbiInterface;
  functions: {
    attack_success: InvokeFunction<[], boolean>;
    hello_world: InvokeFunction<[], void>;
  };
}
