/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export enum ErrorInput { PasswordNotSet = 'PasswordNotSet', WrongPassword = 'WrongPassword' };
export enum ErrorOutput { PasswordNotSet = 'PasswordNotSet', WrongPassword = 'WrongPassword' };

export type VaultAbiConfigurables = {
  PASSWORD: BigNumberish;
};

interface VaultAbiInterface extends Interface {
  functions: {
    attack_success: FunctionFragment;
    unlock: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'attack_success', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'unlock', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'attack_success', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'unlock', data: BytesLike): DecodedValue;
}

export class VaultAbi extends Contract {
  interface: VaultAbiInterface;
  functions: {
    attack_success: InvokeFunction<[], boolean>;
    unlock: InvokeFunction<[password: BigNumberish], void>;
  };
}
