/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.5
  Forc version: 0.63.5
  Fuel-Core version: 0.35.0
*/

export { CounterContract } from './CounterContract';
export { CounterContractFactory } from './CounterContractFactory';
