name: Update Nightly Versions

on:
    schedule:
      # This runs at 12:00 UTC every day Monday through Friday
      - cron: '0 12 * * 1-5'
    # Option to run the workflow manually
    workflow_dispatch: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-nightly-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - uses: FuelLabs/github-actions/setups/node@hf/fix/setup-pnpm
      with:
        node-version: 18.18.2
        pnpm-version: 8.15.7
        pnpm-recursive: false
    - name: Run Script
      run: pnpm docs:update:nightly --from-workflow
