name: Docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
      - name: Lint Check
        run: |
          pnpm install
          pnpm lint:check

  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.34.0
        with:
          config_path: .spellcheck.yml
          task_name: SPCheck